name: SonarCloud Analysis

on:
  push:
    branches:
      - main # Ganti dengan nama branch utama Anda jika berbeda
  pull_request:
    branches:
      - main # Ganti dengan nama branch utama Anda jika berbeda

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Penting agar SonarCloud bisa menganalisis commit dan branch dengan benar
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Gunakan versi Node yang sesuai dengan proyek Anda
          cache: 'npm'

      - name: Verify Node version
        run: node -v

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Install optional dependencies
        run: npm install --no-save --no-audit --no-fund --omit=dev

      - name: Check if vitest exists
        run: ls -l node_modules/.bin

      - name: Make vitest executable
        run: chmod +x node_modules/.bin/vitest

      - name: Run tests and generate coverage
        # Langkah ini WAJIB untuk menghasilkan laporan LCOV sebelum analisis
        run: node_modules/.bin/vitest --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token ini disediakan otomatis oleh GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      # Token yang kita simpan di Langkah 2
