name: SonarCloud Analysis

on:
  push:
    branches:
      - main # Ganti dengan nama branch utama Anda jika berbeda
  pull_request:
    branches:
      - main # Ganti dengan nama branch utama Anda jika berbeda

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Penting agar SonarCloud bisa menganalisis commit dan branch dengan benar
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Gunakan versi Node yang sesuai dengan proyek Anda
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        # Langkah ini WAJIB untuk menghasilkan laporan LCOV sebelum analisis
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token ini disediakan otomatis oleh GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      # Token yang kita simpan di Langkah 2
